spring.application.name=api-gateway

server.port=8080


# ===============================
# Eureka Client Configuration
# ===============================

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# ===============================
# Gateway Discovery Configuration
# ===============================

spring.cloud.gateway.mvc.discovery.locator.enabled=true
spring.cloud.gateway.mvc.discovery.locator.lower-case-service-id=true



# ===============================
# API Gateway Routes
# ===============================


# Patient Service Route

spring.cloud.gateway.mvc.routes[0].id=patient-service

spring.cloud.gateway.mvc.routes[0].uri=lb://patient-service

spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/patients/**



# Doctor Service Route
spring.cloud.gateway.mvc.routes[1].id=doctor-service
spring.cloud.gateway.mvc.routes[1].uri=lb://doctor-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/doctors/**



# Appointment Service Route
spring.cloud.gateway.mvc.routes[2].id=appointment-service
spring.cloud.gateway.mvc.routes[2].uri=lb://appointment-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/appointments/**